# Generated by Django 2.2.2 on 2019-06-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nonce',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='public_address',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
